In [1]:
import numpy as np

1. Write a NumPy program to create a new shape to an array without changing its data.
Arr1 = np.array([1, 21, 32, 43, 54, 65, 5, 44, 10, 11, 12, 13])

In [2]:
Arr1 = np.array([1, 21, 32, 43, 54, 65, 5, 44, 10, 11, 12, 13])

new_shape = (3, 4)  # Desired shape for the array

# Reshape the array without changing its data
reshaped_array = np.reshape(Arr1, new_shape)

print(reshaped_array)


[[ 1 21 32 43]
 [54 65  5 44]
 [10 11 12 13]]


2. Write a NumPy program to change the data type of an array.
Arr2 = np.array([[24, 4, 6, 3], [61, 8, 10, 91]], np.int64)

In [3]:
Arr2 = np.array([[24, 4, 6, 3], [61, 8, 10, 91]], np.int64)

new_dtype = np.float64  # Desired data type for the array

# Change the data type of the array
changed_dtype_array = Arr2.astype(new_dtype)

print(changed_dtype_array.dtype)


float64


3. Write a NumPy program to create an array of 3,5 shape and swap column 2 with column 3.
Arr3 = np.arange(15).reshape(3,5)

In [7]:
Arr3 = np.arange(15).reshape(3, 5)

print("Original Array:")
print(Arr3)

# Swap column 2 with column 3
Arr3[:, [1, 2]] = Arr3[:, [2, 1]]

print("\nSwapping column 2 with column 3:")
print(Arr3)


Original Array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Swapping column 2 with column 3:
[[ 0  2  1  3  4]
 [ 5  7  6  8  9]
 [10 12 11 13 14]]


4. Write a NumPy program to create one-dimensional array of four, five and six digit numbers.

In [5]:
# Create one-dimensional array of four, five, and six-digit numbers
four_digit_array = np.random.randint(1000, 9999, size=10)
five_digit_array = np.random.randint(10000, 99999, size=10)
six_digit_array = np.random.randint(100000, 999999, size=10)

print("Array of Four-Digit Numbers:")
print(four_digit_array)

print("\nArray of Five-Digit Numbers:")
print(five_digit_array)

print("\nArray of Six-Digit Numbers:")
print(six_digit_array)


Array of Four-Digit Numbers:
[1818 7320 7930 1665 1860 9802 2588 3630 3397 3811]

Array of Five-Digit Numbers:
[26839 77689 12878 26505 63396 16511 23568 12717 11421 84402]

Array of Six-Digit Numbers:
[275003 376851 341359 334646 185584 271904 202777 618595 371478 141925]



5. Write a NumPy program to find the missing data in a given array.
Arr4 = np.array([[3, 2, np.nan, np.nan],
 [10, np.nan, 10, np.nan],
 [5, np.nan, 1, np.nan],
 [25, 3, 1, np.nan]])

In [6]:
Arr4 = np.array([[3, 2, np.nan, np.nan],
                 [10, np.nan, 10, np.nan],
                 [5, np.nan, 1, np.nan],
                 [25, 3, 1, np.nan]])

# Find the missing data in the array
missing_data = np.isnan(Arr4)

print("Original Array:")
print(Arr4)

print("\nMissing Data:")
print(missing_data)

Original Array:
[[ 3.  2. nan nan]
 [10. nan 10. nan]
 [ 5. nan  1. nan]
 [25.  3.  1. nan]]

Missing Data:
[[False False  True  True]
 [False  True False  True]
 [False  True False  True]
 [False False False  True]]


6. Write a NumPy program to add a new row to an empty NumPy array.


In [7]:
empty_array = np.empty((0, 3), dtype=int)  # Create an empty 2D array with 3 columns

new_row = np.array([1, 2, 3])  # New row to be added

# Add the new row to the empty array
updated_array = np.vstack((empty_array, new_row))

print("Empty Array:")
print(empty_array)

print("\nNew Row:")
print(new_row)

print("\nUpdated Array:")
print(updated_array)


Empty Array:
[]

New Row:
[1 2 3]

Updated Array:
[[1 2 3]]


7. Write a NumPy program to convert a Python dictionary to a NumPy ndarray.


In [8]:
# Python dictionary
python_dict = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

# Convert dictionary values to ndarray
ndarray = np.array(list(python_dict.values()))

print("Python Dictionary:")
print(python_dict)

print("\nNumPy ndarray:")
print(ndarray)


Python Dictionary:
{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

NumPy ndarray:
[1 2 3 4 5]





8. Write a NumPy program to check whether the dimensions of two given arrays are same or
not.

In [9]:
# Given arrays
arr1 = np.array([[11, 22], [33, 44]])
arr2 = np.array([[55, 66], [77, 88]])
# arr2 = np.array([[55, 66], [77, 88],[2,4]])


# Check if dimensions are the same
same_dimensions = arr1.shape == arr2.shape

print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

if same_dimensions:
    print("\nThe dimensions of the two arrays are the same.")
else:
    print("\nThe dimensions of the two arrays are different.")


Array 1:
[[11 22]
 [33 44]]

Array 2:
[[55 66]
 [77 88]]

The dimensions of the two arrays are the same.
